/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ApocryphaSettings, BiblePassage, DailyReading as DailyReadingType, ProgressTracking, ProviderConfiguration, ReadingPlan } from "./types";
export { ApocryphaSettings, BiblePassage, DailyReading as DailyReadingType, ProgressTracking, ProviderConfiguration, ReadingPlan } from "./types";
export namespace Components {
    interface ApocryphaToggle {
        /**
          * @default {     includeDeuterocanonical: false,     includeNTApocrypha: false,     denominationalPreference: 'protestant',     intertestamentalPlacement: 'historical-gap'   }
         */
        "settings": ApocryphaSettings;
    }
    interface AppRoot {
    }
    interface DailyReading {
        /**
          * @default false
         */
        "compactMode": boolean;
        /**
          * @default 1
         */
        "currentDay": number;
        "reading": DailyReadingType;
        /**
          * @default false
         */
        "readingComplete": boolean;
        /**
          * @default true
         */
        "showHistoricalContext": boolean;
    }
    interface MultiProviderProgress {
        /**
          * @default false
         */
        "compactView": boolean;
        /**
          * @default []
         */
        "progressData": ProgressTracking[];
        /**
          * @default []
         */
        "readingPlans": ReadingPlan[];
    }
    interface ProviderComparison {
        /**
          * @default []
         */
        "providers": ProviderConfiguration[];
        /**
          * @default ''
         */
        "selectedProvider": string;
    }
    interface TestComponent {
    }
}
export interface ApocryphaToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLApocryphaToggleElement;
}
export interface DailyReadingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDailyReadingElement;
}
export interface ProviderComparisonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLProviderComparisonElement;
}
declare global {
    interface HTMLApocryphaToggleElementEventMap {
        "settingsChanged": ApocryphaSettings;
    }
    interface HTMLApocryphaToggleElement extends Components.ApocryphaToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLApocryphaToggleElementEventMap>(type: K, listener: (this: HTMLApocryphaToggleElement, ev: ApocryphaToggleCustomEvent<HTMLApocryphaToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLApocryphaToggleElementEventMap>(type: K, listener: (this: HTMLApocryphaToggleElement, ev: ApocryphaToggleCustomEvent<HTMLApocryphaToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLApocryphaToggleElement: {
        prototype: HTMLApocryphaToggleElement;
        new (): HTMLApocryphaToggleElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDailyReadingElementEventMap {
        "readingCompleted": number;
        "passageSelected": BiblePassage;
    }
    interface HTMLDailyReadingElement extends Components.DailyReading, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDailyReadingElementEventMap>(type: K, listener: (this: HTMLDailyReadingElement, ev: DailyReadingCustomEvent<HTMLDailyReadingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDailyReadingElementEventMap>(type: K, listener: (this: HTMLDailyReadingElement, ev: DailyReadingCustomEvent<HTMLDailyReadingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDailyReadingElement: {
        prototype: HTMLDailyReadingElement;
        new (): HTMLDailyReadingElement;
    };
    interface HTMLMultiProviderProgressElement extends Components.MultiProviderProgress, HTMLStencilElement {
    }
    var HTMLMultiProviderProgressElement: {
        prototype: HTMLMultiProviderProgressElement;
        new (): HTMLMultiProviderProgressElement;
    };
    interface HTMLProviderComparisonElementEventMap {
        "providerSelected": string;
    }
    interface HTMLProviderComparisonElement extends Components.ProviderComparison, HTMLStencilElement {
        addEventListener<K extends keyof HTMLProviderComparisonElementEventMap>(type: K, listener: (this: HTMLProviderComparisonElement, ev: ProviderComparisonCustomEvent<HTMLProviderComparisonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLProviderComparisonElementEventMap>(type: K, listener: (this: HTMLProviderComparisonElement, ev: ProviderComparisonCustomEvent<HTMLProviderComparisonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLProviderComparisonElement: {
        prototype: HTMLProviderComparisonElement;
        new (): HTMLProviderComparisonElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "apocrypha-toggle": HTMLApocryphaToggleElement;
        "app-root": HTMLAppRootElement;
        "daily-reading": HTMLDailyReadingElement;
        "multi-provider-progress": HTMLMultiProviderProgressElement;
        "provider-comparison": HTMLProviderComparisonElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface ApocryphaToggle {
        "onSettingsChanged"?: (event: ApocryphaToggleCustomEvent<ApocryphaSettings>) => void;
        /**
          * @default {     includeDeuterocanonical: false,     includeNTApocrypha: false,     denominationalPreference: 'protestant',     intertestamentalPlacement: 'historical-gap'   }
         */
        "settings"?: ApocryphaSettings;
    }
    interface AppRoot {
    }
    interface DailyReading {
        /**
          * @default false
         */
        "compactMode"?: boolean;
        /**
          * @default 1
         */
        "currentDay"?: number;
        "onPassageSelected"?: (event: DailyReadingCustomEvent<BiblePassage>) => void;
        "onReadingCompleted"?: (event: DailyReadingCustomEvent<number>) => void;
        "reading"?: DailyReadingType;
        /**
          * @default false
         */
        "readingComplete"?: boolean;
        /**
          * @default true
         */
        "showHistoricalContext"?: boolean;
    }
    interface MultiProviderProgress {
        /**
          * @default false
         */
        "compactView"?: boolean;
        /**
          * @default []
         */
        "progressData"?: ProgressTracking[];
        /**
          * @default []
         */
        "readingPlans"?: ReadingPlan[];
    }
    interface ProviderComparison {
        "onProviderSelected"?: (event: ProviderComparisonCustomEvent<string>) => void;
        /**
          * @default []
         */
        "providers"?: ProviderConfiguration[];
        /**
          * @default ''
         */
        "selectedProvider"?: string;
    }
    interface TestComponent {
    }
    interface IntrinsicElements {
        "apocrypha-toggle": ApocryphaToggle;
        "app-root": AppRoot;
        "daily-reading": DailyReading;
        "multi-provider-progress": MultiProviderProgress;
        "provider-comparison": ProviderComparison;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apocrypha-toggle": LocalJSX.ApocryphaToggle & JSXBase.HTMLAttributes<HTMLApocryphaToggleElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "daily-reading": LocalJSX.DailyReading & JSXBase.HTMLAttributes<HTMLDailyReadingElement>;
            "multi-provider-progress": LocalJSX.MultiProviderProgress & JSXBase.HTMLAttributes<HTMLMultiProviderProgressElement>;
            "provider-comparison": LocalJSX.ProviderComparison & JSXBase.HTMLAttributes<HTMLProviderComparisonElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
